# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/ciprian/Documents/Github/Cmod-A7/hw/src/constraints/CmodA7_Master.xdc

# IP: /home/ciprian/Documents/Github/Cmod-A7/hw/src/ip/xadc_wiz_0/xadc_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_wiz_0 || ORIG_REF_NAME==xadc_wiz_0} -quiet] -quiet

# XDC: /home/ciprian/Documents/Github/Cmod-A7/hw/src/ip/xadc_wiz_0/xadc_wiz_0_ooc.xdc

# XDC: /home/ciprian/Documents/Github/Cmod-A7/hw/src/ip/xadc_wiz_0/xadc_wiz_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==xadc_wiz_0 || ORIG_REF_NAME==xadc_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet
